[tool.black]
line-length = 100
target-version = ["py311", "py310", "py39"]

[tool.ruff]
line-length = 100
target-version = "py39"

[tool.ruff.lint]
extend-select = ["I"]
ignore = []

[tool.ruff.lint.isort]
known-first-party = ["tiktoken_vocab_cli"]
combine-as-imports = true

[dependency-groups]
dev = [
    "black>=24.0.0",
    "pre-commit>=3.7.0",
    "pytest>=8.0.0",
    "ruff>=0.6.0",
]
